version: '2'
services:
    #db:
    #    build: db
    #    restart: always
    #    env_file: 
    #        - ./common.env
    #        - ./db/secrets.env
    #    volumes:
    #        - pg_data:/var/lib/postgresql/data

    proxy:
        build: proxy
        restart: always
        depends_on:
            - api
            - jbrowse
            - web
        links:
            - api
            - jbrowse
            - web
        ports:
            - "127.0.0.1:7000:80"
        volumes:
            - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/nginx/conf.d:/etc/nginx/conf.d

    jbrowse:
        image: jbrowse/gmod-jbrowse
        restart: always
        volumes:
            - jbrowse_data:/data

    web:
        build: web
        restart: always
        volumes:
            - ./web:/app

    api:
        build: api 
        restart: always
        env_file:
            - ./common.env
              #- ./db/secrets.env
        volumes:
            - ./api:/app
            - jbrowse_data:/jbrowse
            - results:/results
            - ./data/indices:/indices
            - ./data/fasta:/fasta

        depends_on:
            - exec
        links:
            - exec
    exec:
        build: exec
        env_file:
            - ./common.env
        volumes:
            - ./exec/blast_worker.pl:/blast_worker.pl
            - beanstalkd:/data
            - results:/results
            - ./data/indices:/indices
            - ./data/fasta:/fasta

volumes:
    #pg_data:
    jbrowse_data:
    results:
    beanstalkd:
