version: '2'
services:
    db:
        image: redis
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - redis_data:/data
    proxy:
        build: proxy
        restart: always
        depends_on:
            - api
            - web
        links:
            - api
            - web
        ports:
            - 7001:80
        volumes:
            - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/nginx/conf.d:/etc/nginx/conf.d
    web:
        build: web
        restart: always
        volumes:
            - ./web:/app

    api:
        build: api 
        restart: always
        env_file:
            - ./common.env
            #- ./db/secrets.env
        volumes:
            - ./api:/app
            - results:/results
            - ./data/indices:/indices
            - ./data/fasta:/fasta

        depends_on:
            - exec
            - db
        links:
            - exec
            - db
    exec:
        build: exec
        env_file:
            - ./common.env
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./exec:/app
            - results:/results
            - ./data/indices:/indices
            - ./data/fasta:/fasta

volumes:
    results:
    redis_data:
