#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB_ADMIN with PASSWORD '$DB_ADMIN_PASSWORD';
    CREATE USER $WEB_DB_USER with PASSWORD '$WEB_DB_PASSWORD';
    CREATE DATABASE $JOB_DB;
    GRANT ALL PRIVILEGES ON DATABASE $JOB_DB TO $DB_ADMIN;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" $JOB_DB <<-EOSQL
    CREATE TABLE info (
        id   serial,
        data jsonb
    );
    CREATE UNIQUE INDEX id_idx on info (id);

    GRANT SELECT,INSERT,UPDATE ON TABLE info TO $WEB_DB_USER;
    GRANT ALL PRIVILEGES ON SEQUENCE info_id_seq TO $WEB_DB_USER;

    GRANT ALL PRIVILEGES ON TABLE info to $DB_ADMIN;
    GRANT ALL PRIVILEGES ON SEQUENCE info_id_seq to $DB_ADMIN;
EOSQL

